#!/bin/bash
for i in file_get file_change file_save get_project move; do
	f=./"$i".py
	timeout 10s python3 "$f"
	if [ $? -ne 0 ]; then
		echo "TEST FAILED: $f"
	fi
done
clear
echo ----
python3 lock.py
