.PHONY: default clean

#CC?=gcc
#CFLAGS=-Wall -Wextra -pedantic -std=gnu99 $(shell pkg-config --cflags sdl2)
#LDFLAGS=$(shell pkg-config --libs sdl2)

default: ui_editor
ui_editor: ui_editor.c
	x86_64-w64-mingw32-gcc -Wall -Wextra -pedantic -std=gnu99     ui_editor.c -o ui_editor -I"/usr/local/x86_64-w64-mingw32/include/" -I"/usr/local/include/" -L"/usr/local/x86_64-w64-mingw32/lib/" -L"/usr/local/lib" -lSDL2_image -lSDL2 -mwin32 -lglew32 -lopengl32 -lglu32

clean:
	rm -f ui_editor *.o
